//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_sklad_app.AppDataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class klients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klients()
        {
            this.prodanniy_tovar = new HashSet<prodanniy_tovar>();
        }
    
        public int id_klient { get; set; }
        public string name { get; set; }
        public string addres { get; set; }
        public string contact { get; set; }
        public Nullable<int> INN { get; set; }
        public Nullable<int> Raschetniy_schet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prodanniy_tovar> prodanniy_tovar { get; set; }
    }
}
