//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_sklad_app.AppDataFiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skald_dbEntities : DbContext
    {
        private static skald_dbEntities _context;
        public skald_dbEntities()
            : base("name=skald_dbEntities")
        {
        }
        public static skald_dbEntities GetContext()
        {
            if (_context == null)
                _context = new skald_dbEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<klients> klients { get; set; }
        public virtual DbSet<postavlenniy_tovar> postavlenniy_tovar { get; set; }
        public virtual DbSet<postavshiki> postavshiki { get; set; }
        public virtual DbSet<prodanniy_tovar> prodanniy_tovar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tovar__nalichii> tovar__nalichii { get; set; }
    }
}
