//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_sklad_app.AppDataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class postavshiki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public postavshiki()
        {
            this.postavlenniy_tovar = new HashSet<postavlenniy_tovar>();
        }
    
        public int id_postavshiki { get; set; }
        public string name { get; set; }
        public string addres { get; set; }
        public string contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<postavlenniy_tovar> postavlenniy_tovar { get; set; }
    }
}
