//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_sklad_app.AppDataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class postavlenniy_tovar
    {
        public int id_postavlenniy_tovar { get; set; }
        public string name { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> date_postav { get; set; }
        public Nullable<int> id_postavshik { get; set; }
        public Nullable<int> id_prihodnoy_nakladnoy { get; set; }
        public Nullable<float> price_one_product { get; set; }
        public Nullable<float> summ { get; set; }
    
        public virtual postavshiki postavshiki { get; set; }
        public virtual prodanniy_tovar prodanniy_tovar { get; set; }
        public virtual tovar__nalichii tovar__nalichii { get; set; }
    }
}
