//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_sklad_app.AppDataFiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar__nalichii
    {
        public int id_tovar_vnalichii { get; set; }
        public string name { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> id_postavlenniy_tovar { get; set; }
    
        public virtual postavlenniy_tovar postavlenniy_tovar { get; set; }
    }
}
